### ISSUE TITLE
UnhandledRejection: request error nvim_call_function - buffer does not exist!

### ISSUE THREAD

**Issue by PetrusZ** [neoclide/coc-yank#19]
Use command `CocList -A --normal yank` got a lot of error:

```
[coc.nvim] error: UnhandledRejection: request error nvim_call_function - buffer does not exist!
[coc.nvim] error: Error: request error nvim_call_function - buffer does not exist!
[coc.nvim] error:     at /home/petrus/.vim/plugged/coc.nvim/node_modules/@chemzqm/neovim/lib/api/Base.js:40:32
[coc.nvim] error:     at Request.callback (/home/petrus/.vim/plugged/coc.nvim/node_modules/@chemzqm/neovim/lib/transpor
t/request.js:24:20)
[coc.nvim] error:     at Connection.<anonymous> (/home/petrus/.vim/plugged/coc.nvim/node_modules/@chemzqm/neovim/lib/tr
ansport/vim.js:42:21)
[coc.nvim] error:     at Connection.emit (events.js:321:20)
[coc.nvim] error:     at Connection.parseData (/home/petrus/.vim/plugged/coc.nvim/node_modules/@chemzqm/neovim/lib/tran
sport/connection.js:48:18)
[coc.nvim] error:     at Interface.<anonymous> (/home/petrus/.vim/plugged/coc.nvim/node_modules/@chemzqm/neovim/lib/tra
nsport/connection.js:18:18)
[coc.nvim] error:     at Interface.emit (events.js:321:20)
[coc.nvim] error:     at Interface._onLine (readline.js:327:10)
[coc.nvim] error:     at Interface._normalWrite (readline.js:472:12)
[coc.nvim] error:     at Socket.ondata (readline.js:184:10)
[coc.nvim] error: UnhandledRejection: request error nvim_call_function - buffer does not exist!
[coc.nvim] error: Error: request error nvim_call_function - buffer does not exist!
[coc.nvim] error:     at /home/petrus/.vim/plugged/coc.nvim/node_modules/@chemzqm/neovim/lib/api/Base.js:40:32
[coc.nvim] error:     at Request.callback (/home/petrus/.vim/plugged/coc.nvim/node_modules/@chemzqm/neovim/lib/transpor
t/request.js:24:20)
[coc.nvim] error:     at Connection.<anonymous> (/home/petrus/.vim/plugged/coc.nvim/node_modules/@chemzqm/neovim/lib/tr
ansport/vim.js:42:21)
[coc.nvim] error:     at Connection.emit (events.js:321:20)
[coc.nvim] error:     at Connection.parseData (/home/petrus/.vim/plugged/coc.nvim/node_modules/@chemzqm/neovim/lib/tran
sport/connection.js:48:18)
[coc.nvim] error:     at Interface.<anonymous> (/home/petrus/.vim/plugged/coc.nvim/node_modules/@chemzqm/neovim/lib/tra
nsport/connection.js:18:18)
[coc.nvim] error:     at Interface.emit (events.js:321:20)
[coc.nvim] error:     at Interface._onLine (readline.js:327:10)
[coc.nvim] error:     at Interface._normalWrite (readline.js:472:12)
[coc.nvim] error:     at Socket.ondata (readline.js:184:10)
```

But, `CocList --normal yank` works fine.

**Comment by chemzqm** [comment]
Can't reproduce.
