### ISSUE TITLE
Highlight stopped working

### ISSUE THREAD

**Issue by jfpedroza** [neoclide/coc-yank#33]
Highlight stopped working after an update some time ago.

This is what appears using `CocOpenLog`:

```
2021-04-02T04:13:48.933 ERROR (pid:370850) [plugin] - Error on autocmd TextYankPost TypeError: doc.matchAddRanges is not a function
    at Object.<anonymous> (/home/jhon/.config/coc/extensions/node_modules/coc-yank/lib/index.js:182:35)
    at Generator.next (<anonymous>)
    at fulfilled (/home/jhon/.config/coc/extensions/node_modules/coc-yank/lib/index.js:95:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
2021-04-02T04:13:48.933 ERROR (pid:370850) [node-client] - resumeNotification not called within same tick: Error
    at tM.pauseNotification (/home/jhon/.local/share/nvim/plugged/coc.nvim/build/index.js:23:4591)
    at Object.<anonymous> (/home/jhon/.config/coc/extensions/node_modules/coc-yank/lib/index.js:181:26)
    at Generator.next (<anonymous>)
    at fulfilled (/home/jhon/.config/coc/extensions/node_modules/coc-yank/lib/index.js:95:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by chemzqm** [comment]
Please upgrade your coc.nvim.

**Comment by jfpedroza** [comment]
That did it, thanks. I didn't realize the extensions hadn't updated automatically

**Comment by liujoey** [comment]
I struggled by this issue many days until today I realized that I didn't update my coc extensions.
Every time i had this issue I try to upgrade nvim to newer nightly build, also run PlugUpdate to update all plugins but with no luck.
I think I should set up the coc.nvim such that every time i update coc.nvim it should automatically update all extensions.
